// deno-fmt-ignore-file
// biome-ignore format: generated types do not need formatting
// prettier-ignore
import type { PathsForPages } from 'waku/router'

// prettier-ignore
type Page =
  | { path: '/concepts/architecture/caliber/base-tokens'; render: 'static' }
  | { path: '/concepts/architecture/caliber/caliber-accounting'; render: 'static' }
  | { path: '/concepts/architecture/caliber/flash-loans'; render: 'static' }
  | { path: '/concepts/architecture/caliber/harvests'; render: 'static' }
  | { path: '/concepts/architecture/caliber/makina-vm'; render: 'static' }
  | { path: '/concepts/architecture/caliber/overview'; render: 'static' }
  | { path: '/concepts/architecture/caliber/positions'; render: 'static' }
  | { path: '/concepts/architecture/caliber/swaps'; render: 'static' }
  | { path: '/concepts/architecture/cross-chain/caliber-mailbox'; render: 'static' }
  | { path: '/concepts/architecture/cross-chain/cross-chain-accounting'; render: 'static' }
  | { path: '/concepts/architecture/cross-chain/hub-and-spoke'; render: 'static' }
  | { path: '/concepts/architecture/cross-chain/liquidity-bridging'; render: 'static' }
  | { path: '/concepts/architecture/lifecycle'; render: 'static' }
  | { path: '/concepts/architecture/machine/deposits'; render: 'static' }
  | { path: '/concepts/architecture/machine/fees'; render: 'static' }
  | { path: '/concepts/architecture/machine/machine-token'; render: 'static' }
  | { path: '/concepts/architecture/machine/overview'; render: 'static' }
  | { path: '/concepts/architecture/machine/pre-deposit'; render: 'static' }
  | { path: '/concepts/architecture/machine/redemptions'; render: 'static' }
  | { path: '/concepts/architecture/machine/share-price'; render: 'static' }
  | { path: '/concepts/architecture/overview'; render: 'static' }
  | { path: '/concepts/architecture/pricing-oracles'; render: 'static' }
  | { path: '/concepts/governance/operator'; render: 'static' }
  | { path: '/concepts/governance/overview'; render: 'static' }
  | { path: '/concepts/governance/permissions-and-scopes'; render: 'static' }
  | { path: '/concepts/governance/protocol-upgrades'; render: 'static' }
  | { path: '/concepts/governance/risk-manager'; render: 'static' }
  | { path: '/concepts/governance/root-update-lifecycle'; render: 'static' }
  | { path: '/concepts/governance/safe-security-structure'; render: 'static' }
  | { path: '/concepts/governance/security-council'; render: 'static' }
  | { path: '/concepts/introduction'; render: 'static' }
  | { path: '/concepts/security/recovery-mode'; render: 'static' }
  | { path: '/concepts/security/security-module'; render: 'static' }
  | { path: '/concepts/security/trust-and-risk'; render: 'static' }
  | { path: '/contracts/core/architecture-overview'; render: 'static' }
  | { path: '/contracts/core/bridge/adapters/abstract.BridgeAdapter'; render: 'static' }
  | { path: '/contracts/core/bridge/adapters/contract.AcrossV3BridgeAdapter'; render: 'static' }
  | { path: '/contracts/core/bridge/adapters/contract.CctpV2BridgeAdapter'; render: 'static' }
  | { path: '/contracts/core/bridge/adapters/contract.LayerZeroV2BridgeAdapter'; render: 'static' }
  | { path: '/contracts/core/bridge/configs/contract.AcrossV3BridgeConfig'; render: 'static' }
  | { path: '/contracts/core/bridge/configs/contract.CctpV2BridgeConfig'; render: 'static' }
  | { path: '/contracts/core/bridge/configs/contract.LayerZeroV2BridgeConfig'; render: 'static' }
  | { path: '/contracts/core/bridge/controller/abstract.BridgeController'; render: 'static' }
  | { path: '/contracts/core/caliber/contract.Caliber'; render: 'static' }
  | { path: '/contracts/core/caliber/contract.CaliberMailbox'; render: 'static' }
  | { path: '/contracts/core/deployments'; render: 'static' }
  | { path: '/contracts/core/factories/abstract.BridgeAdapterFactory'; render: 'static' }
  | { path: '/contracts/core/factories/abstract.CaliberFactory'; render: 'static' }
  | { path: '/contracts/core/factories/abstract.Create3Factory'; render: 'static' }
  | { path: '/contracts/core/factories/contract.HubCoreFactory'; render: 'static' }
  | { path: '/contracts/core/factories/contract.SpokeCoreFactory'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.AggregatorV2V3Interface'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IAcrossV3BridgeConfig'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IAcrossV3MessageHandler'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IAcrossV3SpokePool'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IBridgeAdapter'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IBridgeAdapterFactory'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IBridgeConfig'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IBridgeController'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ICaliber'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ICaliberFactory'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ICaliberMailbox'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ICctpV2BridgeConfig'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ICctpV2DestinationCaller'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ICctpV2MessageTransmitter'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ICctpV2TokenMessenger'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ICctpV2TokenMinter'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ICoreRegistry'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ICreReceiver'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IFeeManager'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IHubCoreFactory'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IHubCoreRegistry'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ILayerZeroComposer'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ILayerZeroV2BridgeConfig'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IMachine'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IMachineEndpoint'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IMachineShare'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IMakinaContext'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IMakinaGovernable'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IOracleRegistry'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IOwnable2Step'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IPreDepositVault'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ISpokeCoreFactory'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ISpokeCoreRegistry'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ISpokeSnapshotConsumer'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ISwapModule'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.ITokenRegistry'; render: 'static' }
  | { path: '/contracts/core/interfaces/interface.IWeirollVM'; render: 'static' }
  | { path: '/contracts/core/libraries/library.CctpV2Message'; render: 'static' }
  | { path: '/contracts/core/libraries/library.DecimalsUtils'; render: 'static' }
  | { path: '/contracts/core/libraries/library.Errors'; render: 'static' }
  | { path: '/contracts/core/libraries/library.LzOptionsBuilder'; render: 'static' }
  | { path: '/contracts/core/libraries/library.MachineUtils'; render: 'static' }
  | { path: '/contracts/core/libraries/library.Roles'; render: 'static' }
  | { path: '/contracts/core/machine/contract.Machine'; render: 'static' }
  | { path: '/contracts/core/machine/contract.MachineShare'; render: 'static' }
  | { path: '/contracts/core/pre-deposit/contract.PreDepositVault'; render: 'static' }
  | { path: '/contracts/core/registries/abstract.CoreRegistry'; render: 'static' }
  | { path: '/contracts/core/registries/contract.HubCoreRegistry'; render: 'static' }
  | { path: '/contracts/core/registries/contract.OracleRegistry'; render: 'static' }
  | { path: '/contracts/core/registries/contract.SpokeCoreRegistry'; render: 'static' }
  | { path: '/contracts/core/registries/contract.TokenRegistry'; render: 'static' }
  | { path: '/contracts/core/summary'; render: 'static' }
  | { path: '/contracts/core/swap/contract.SwapModule'; render: 'static' }
  | { path: '/contracts/core/utils/abstract.MakinaContext'; render: 'static' }
  | { path: '/contracts/core/utils/abstract.MakinaGovernable'; render: 'static' }
  | { path: '/contracts/core/utils/abstract.SpokeSnapshotConsumer'; render: 'static' }
  | { path: '/contracts/periphery/architecture-overview'; render: 'static' }
  | { path: '/contracts/periphery/deployments'; render: 'static' }
  | { path: '/contracts/periphery/depositors/contract.DirectDepositor'; render: 'static' }
  | { path: '/contracts/periphery/factories/contract.HubPeripheryFactory'; render: 'static' }
  | { path: '/contracts/periphery/factories/contract.MachineShareOracleFactory'; render: 'static' }
  | { path: '/contracts/periphery/factories/contract.MetaMorphoOracleFactory'; render: 'static' }
  | { path: '/contracts/periphery/fee-managers/contract.WatermarkFeeManager'; render: 'static' }
  | { path: '/contracts/periphery/flashloans/contract.FlashloanAggregator'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IAsyncRedeemer'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IAsyncRedeemerFee'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IChainalysisSanctionsList'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IDirectDepositor'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IFlashloanAggregator'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IHubPeripheryFactory'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IHubPeripheryRegistry'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IMachinePeriphery'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IMachineShareOracle'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IMachineShareOracleFactory'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IMakinaPeripheryContext'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IMetaMorphoFactory'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IMetaMorphoOracleFactory'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.ISMCooldownReceipt'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.ISanctionsList'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.ISecurityModule'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.ISecurityModuleReference'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IShareTokenOwner'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IWatermarkFeeManager'; render: 'static' }
  | { path: '/contracts/periphery/interfaces/interface.IWhitelist'; render: 'static' }
  | { path: '/contracts/periphery/libraries/library.Errors'; render: 'static' }
  | { path: '/contracts/periphery/oracles/contract.ERC4626Oracle'; render: 'static' }
  | { path: '/contracts/periphery/oracles/contract.MachineShareOracle'; render: 'static' }
  | { path: '/contracts/periphery/redeemers/contract.AsyncRedeemer'; render: 'static' }
  | { path: '/contracts/periphery/redeemers/contract.AsyncRedeemerFee'; render: 'static' }
  | { path: '/contracts/periphery/registries/contract.HubPeripheryRegistry'; render: 'static' }
  | { path: '/contracts/periphery/security-module/contract.SMCooldownReceipt'; render: 'static' }
  | { path: '/contracts/periphery/security-module/contract.SecurityModule'; render: 'static' }
  | { path: '/contracts/periphery/summary'; render: 'static' }
  | { path: '/contracts/periphery/utils/abstract.MachinePeriphery'; render: 'static' }
  | { path: '/contracts/periphery/utils/abstract.MakinaPeripheryContext'; render: 'static' }
  | { path: '/contracts/periphery/utils/abstract.SanctionsList'; render: 'static' }
  | { path: '/contracts/periphery/utils/abstract.Whitelist'; render: 'static' }
  | { path: '/contracts/periphery/weiroll-helpers/contract.BooleanHelper'; render: 'static' }
  | { path: '/contracts/periphery/weiroll-helpers/contract.Bytes32Helper'; render: 'static' }
  | { path: '/contracts/periphery/weiroll-helpers/contract.CastHelper'; render: 'static' }
  | { path: '/contracts/periphery/weiroll-helpers/contract.ContextHelper'; render: 'static' }
  | { path: '/contracts/periphery/weiroll-helpers/contract.KeyValueStore'; render: 'static' }
  | { path: '/contracts/periphery/weiroll-helpers/contract.MathHelper'; render: 'static' }
  | { path: '/contracts/periphery/weiroll-helpers/contract.SignedMathHelper'; render: 'static' }
  | { path: '/contracts/safe-harbor'; render: 'static' }
  | { path: '/contracts/security'; render: 'static' }
  | { path: '/'; render: 'static' }
  | { path: '/strategies/deployments'; render: 'static' }

// prettier-ignore
declare module 'waku/router' {
  interface RouteConfig {
    paths: PathsForPages<Page>
  }
  interface CreatePagesConfig {
    pages: Page
  }
}
